### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by manoeltroia** [srlesrle/betting#4]
Warning: mail(): SMTP server response: 553 We do not relay non-local mail, sorry. in C:\xampp\htdocs\application\errors\error_php.php on line 11
A PHP Error was encountered
Severity: Notice

Message: Notice
Only variable references should be returned by reference
core/Common.php
257

Filename: core/Common.php

Line Number: 257

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; MY_Log has a deprecated constructor in C:\xampp\htdocs\application\libraries\MY_Log.php on line 2

Notice: Undefined variable: message in C:\xampp\htdocs\application\libraries\MY_Log.php on line 16

Fatal error: Uncaught Error: Class 'CI_Controller' not found in C:\xampp\htdocs\system\core\CodeIgniter.php:233 Stack trace: #0 C:\xampp\htdocs\application\libraries\MY_Log.php(17): get_instance() #1 C:\xampp\htdocs\system\core\Common.php(359): MY_Log->write_log('error', 'Severity: Notic...', true) #2 C:\xampp\htdocs\system\core\Exceptions.php(91): log_message('error', 'Severity: Notic...', true) #3 C:\xampp\htdocs\system\core\Common.php(496): CI_Exceptions->log_exception('Notice', 'Only variable r...', 'C:\\xampp\\htdocs...', 257) #4 C:\xampp\htdocs\system\core\Common.php(257): _exception_handler(8, 'Only variable r...', 'C:\\xampp\\htdocs...', 257, Array) #5 C:\xampp\htdocs\system\core\Common.php(277): get_config() #6 C:\xampp\htdocs\system\core\Common.php(153): config_item('subclass_prefix') #7 C:\xampp\htdocs\system\core\CodeIgniter.php(115): load_class('Benchmark', 'core') #8 C:\xampp\htdocs\index.php(204): require_once('C:\\xampp\\htdocs...') #9 {main} thrown in C:\xampp\htdocs\system\core\CodeIgniter.php on line 233

**Comment by manoeltroia** [comment]
upload new files correct or put one guide pleaseeee helppp... what name db i need put?

**Comment by manoeltroia** [comment]
send u facebook or instagram or whatsapp

**Comment by NorinMp143** [comment]
hey, you can check here...
https://stackoverflow.com/questions/6809369/warning-mail-function-mail-smtp-server-response-553-we-do-not-relay-non-l/18119492

https://www.researchgate.net/post/How_do_you_solve_the_problem_Warning_mail_SMTP_server_response_530_Authentication_required_in_Cwampwwwsammailphp_on_line_20_in_php
